// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/modules/lexical/LangLex.jflex

/*
    Grupo: Marcos Mateus Oliveira dos Santos - 201835019
           Giovane Nilmer de Oliveira Santos - 201835012

*/


 /*  Esta seção é copiada antes da declaração da classe do analisador léxico.
  *  É nesta seção que se deve incluir imports e declaração de pacotes.
  */
  

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u1100\1\u1200\1\u1300\1\u1400\1\u1100\1\u1500\1\u1600"+
    "\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u1c00\1\u1d00\1\u1e00"+
    "\1\u1f00\1\u2000\2\u2100\1\u2200\7\u2100\1\u2300\1\u2400\1\u2500"+
    "\1\u2100\1\u2600\1\u2700\2\u2100\31\u1100\1\u2800\121\u1100\1\u2900"+
    "\4\u1100\1\u2a00\1\u1100\1\u2b00\1\u2c00\1\u2d00\1\u2e00\1\u2f00"+
    "\1\u3000\53\u1100\1\u3100\10\u3200\31\u2100\1\u1100\1\u3300\1\u3400"+
    "\1\u1100\1\u3500\1\u3600\1\u3700\1\u3800\1\u2100\1\u3900\1\u3a00"+
    "\1\u3b00\1\u3c00\1\u1100\1\u3d00\1\u3e00\1\u3f00\1\u4000\1\u4100"+
    "\1\u4200\1\u4300\1\u2100\1\u4400\1\u4500\1\u4600\1\u4700\1\u4800"+
    "\1\u4900\1\u4a00\1\u4b00\1\u4c00\1\u4d00\1\u4e00\1\u4f00\1\u2100"+
    "\1\u5000\1\u5100\1\u5200\1\u2100\3\u1100\1\u5300\1\u5400\1\u5500"+
    "\12\u2100\4\u1100\1\u5600\17\u2100\2\u1100\1\u5700\41\u2100\2\u1100"+
    "\1\u5800\1\u5900\2\u2100\1\u5a00\1\u5b00\27\u1100\1\u5c00\2\u1100"+
    "\1\u5d00\45\u2100\1\u1100\1\u5e00\1\u5f00\11\u2100\1\u6000\27\u2100"+
    "\1\u6100\1\u6200\1\u6300\1\u6400\11\u2100\1\u6500\1\u6600\5\u2100"+
    "\1\u6700\1\u6800\4\u2100\1\u6900\2\u2100\1\u6a00\16\u2100\246\u1100"+
    "\1\u6b00\20\u1100\1\u6c00\1\u6d00\25\u1100\1\u6e00\34\u1100\1\u6f00"+
    "\14\u2100\2\u1100\1\u7000\u0e05\u2100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\3\0\1\7\1\10\1\11\2\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\12\21\1\22\1\23\1\24"+
    "\1\25\1\26\2\0\1\27\1\30\1\31\2\27\1\32"+
    "\2\27\1\33\21\27\1\34\1\35\1\36\1\0\1\37"+
    "\1\0\1\40\2\41\1\42\1\43\1\44\1\41\1\45"+
    "\1\46\2\41\1\47\1\41\1\50\1\51\1\52\1\41"+
    "\1\53\1\54\1\55\1\56\1\41\1\57\3\41\1\60"+
    "\1\0\1\61\7\0\1\3\44\0\1\41\12\0\1\41"+
    "\4\0\1\41\5\0\27\27\1\0\7\27\30\41\1\0"+
    "\10\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\2\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\2\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\2\27"+
    "\1\41\1\27\1\41\1\27\3\41\2\27\1\41\1\27"+
    "\1\41\2\27\1\41\3\27\2\41\4\27\1\41\2\27"+
    "\1\41\3\27\3\41\2\27\1\41\2\27\1\41\1\27"+
    "\1\41\1\27\1\41\2\27\1\41\1\27\2\41\1\27"+
    "\1\41\2\27\1\41\3\27\1\41\1\27\1\41\2\27"+
    "\2\41\1\62\1\27\3\41\4\62\1\27\1\62\1\41"+
    "\1\27\1\62\1\41\1\27\1\62\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\2\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\2\41"+
    "\1\27\1\62\1\41\1\27\1\41\3\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\7\41\2\27\1\41\2\27\2\41\1\27\1\41\4\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\105\41\1\62\44\41\7\62\2\41\4\0\14\62\16\0"+
    "\5\41\7\0\1\62\1\0\1\62\126\0\1\63\52\0"+
    "\1\27\1\41\1\27\1\41\1\62\1\0\1\27\1\41"+
    "\2\0\4\41\1\0\1\27\6\0\1\27\1\0\3\27"+
    "\1\0\1\27\1\0\2\27\1\41\21\27\1\0\11\27"+
    "\43\41\1\27\2\41\3\27\3\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\5\41\1\27\1\41\1\0"+
    "\1\27\1\41\2\27\2\41\63\27\60\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\10\0\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\2\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\2\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\0\46\27\2\0"+
    "\1\62\6\0\51\41\107\0\33\62\4\0\4\62\55\0"+
    "\53\62\25\0\12\21\4\0\2\62\1\0\143\62\1\0"+
    "\1\62\17\0\2\62\7\0\2\62\12\21\3\62\2\0"+
    "\1\62\20\0\1\62\1\0\36\62\35\0\131\62\13\0"+
    "\1\62\16\0\12\21\41\62\11\0\2\62\4\0\1\62"+
    "\5\0\26\62\4\0\1\62\11\0\1\62\3\0\1\62"+
    "\27\0\31\62\7\0\13\62\65\0\25\62\1\0\10\62"+
    "\106\0\66\62\3\0\1\62\22\0\1\62\7\0\12\62"+
    "\4\0\12\21\1\0\20\62\4\0\10\62\2\0\2\62"+
    "\2\0\26\62\1\0\7\62\1\0\1\62\3\0\4\62"+
    "\3\0\1\62\20\0\1\62\15\0\2\62\1\0\3\62"+
    "\4\0\12\21\2\62\12\0\1\62\10\0\6\62\4\0"+
    "\2\62\2\0\26\62\1\0\7\62\1\0\2\62\1\0"+
    "\2\62\1\0\2\62\37\0\4\62\1\0\1\62\7\0"+
    "\12\21\2\0\3\62\20\0\11\62\1\0\3\62\1\0"+
    "\26\62\1\0\7\62\1\0\2\62\1\0\5\62\3\0"+
    "\1\62\22\0\1\62\17\0\2\62\4\0\12\21\11\0"+
    "\1\62\13\0\10\62\2\0\2\62\2\0\26\62\1\0"+
    "\7\62\1\0\2\62\1\0\5\62\3\0\1\62\36\0"+
    "\2\62\1\0\3\62\4\0\12\21\1\0\1\62\21\0"+
    "\1\62\1\0\6\62\3\0\3\62\1\0\4\62\3\0"+
    "\2\62\1\0\1\62\1\0\2\62\3\0\2\62\3\0"+
    "\3\62\3\0\14\62\26\0\1\62\25\0\12\21\25\0"+
    "\10\62\1\0\3\62\1\0\27\62\1\0\20\62\3\0"+
    "\1\62\32\0\3\62\5\0\2\62\4\0\12\21\20\0"+
    "\1\62\4\0\10\62\1\0\3\62\1\0\27\62\1\0"+
    "\12\62\1\0\5\62\3\0\1\62\40\0\1\62\1\0"+
    "\2\62\4\0\12\21\1\0\2\62\22\0\10\62\1\0"+
    "\3\62\1\0\51\62\2\0\1\62\20\0\1\62\5\0"+
    "\3\62\10\0\3\62\4\0\12\21\12\0\6\62\5\0"+
    "\22\62\3\0\30\62\1\0\11\62\1\0\1\62\2\0"+
    "\7\62\37\0\12\21\21\0\60\62\1\0\2\62\14\0"+
    "\7\62\11\0\12\21\47\0\2\62\1\0\1\62\1\0"+
    "\5\62\1\0\30\62\1\0\1\62\1\0\12\62\1\0"+
    "\2\62\11\0\1\62\2\0\5\62\1\0\1\62\11\0"+
    "\12\21\2\0\4\62\40\0\1\62\37\0\12\21\26\0"+
    "\10\62\1\0\44\62\33\0\5\62\163\0\53\62\24\0"+
    "\1\62\12\21\6\0\6\62\4\0\4\62\3\0\1\62"+
    "\3\0\2\62\7\0\3\62\4\0\15\62\14\0\1\62"+
    "\1\0\12\21\6\0\46\27\1\0\1\27\5\0\1\27"+
    "\2\0\53\41\1\0\1\62\3\41\u0149\62\1\0\4\62"+
    "\2\0\7\62\1\0\1\62\1\0\4\62\2\0\51\62"+
    "\1\0\4\62\2\0\41\62\1\0\4\62\2\0\7\62"+
    "\1\0\1\62\1\0\4\62\2\0\17\62\1\0\71\62"+
    "\1\0\4\62\2\0\103\62\45\0\20\62\20\0\126\27"+
    "\2\0\6\41\3\0\u016c\62\2\0\21\62\1\0\32\62"+
    "\5\0\113\62\6\0\10\62\7\0\15\62\1\0\4\62"+
    "\16\0\22\62\16\0\22\62\16\0\15\62\1\0\3\62"+
    "\17\0\64\62\43\0\1\62\4\0\1\62\3\0\12\21"+
    "\46\0\12\21\6\0\131\62\7\0\5\62\2\0\42\62"+
    "\1\0\1\62\5\0\106\62\12\0\37\62\47\0\12\21"+
    "\36\62\2\0\5\62\13\0\54\62\4\0\32\62\6\0"+
    "\12\21\46\0\27\62\11\0\65\62\53\0\12\21\6\0"+
    "\12\21\15\0\1\62\135\0\57\62\21\0\7\62\4\0"+
    "\12\21\51\0\36\62\15\0\2\62\12\21\54\62\32\0"+
    "\44\62\34\0\12\21\3\0\3\62\12\21\44\62\2\0"+
    "\11\41\7\0\53\27\2\0\3\27\51\0\4\62\1\0"+
    "\6\62\1\0\2\62\3\0\1\62\5\0\300\41\100\0"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\11\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\11\41"+
    "\10\27\6\41\2\0\6\27\2\0\10\41\10\27\10\41"+
    "\10\27\6\41\2\0\6\27\2\0\10\41\1\0\1\27"+
    "\1\0\1\27\1\0\1\27\1\0\1\27\10\41\10\27"+
    "\16\41\2\0\10\41\10\62\10\41\10\62\10\41\10\62"+
    "\5\41\1\0\2\41\4\27\1\62\1\0\1\41\3\0"+
    "\3\41\1\0\2\41\4\27\1\62\3\0\4\41\2\0"+
    "\2\41\4\27\4\0\10\41\5\27\5\0\3\41\1\0"+
    "\2\41\4\27\1\62\53\0\2\3\107\0\1\41\15\0"+
    "\1\41\20\0\15\41\145\0\1\27\4\0\1\27\2\0"+
    "\1\41\3\27\2\41\3\27\1\41\1\0\1\27\3\0"+
    "\5\27\6\0\1\27\1\0\1\27\1\0\1\27\1\0"+
    "\4\27\1\0\1\41\4\27\1\41\4\62\1\41\2\0"+
    "\2\41\2\27\5\0\1\27\4\41\4\0\1\41\21\0"+
    "\20\64\20\63\3\0\1\27\1\41\u0231\0\32\64\32\63"+
    "\26\0\57\27\1\0\57\41\1\0\1\27\1\41\3\27"+
    "\2\41\1\27\1\41\1\27\1\41\1\27\1\41\4\27"+
    "\1\41\1\27\2\41\1\27\10\41\3\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\2\41\6\0\1\27\1\41\1\27\1\41\3\0\1\27"+
    "\1\41\14\0\46\41\1\0\1\41\5\0\1\41\2\0"+
    "\70\62\7\0\1\62\20\0\27\62\11\0\7\62\1\0"+
    "\7\62\1\0\7\62\1\0\7\62\1\0\7\62\1\0"+
    "\7\62\1\0\7\62\1\0\7\62\120\0\1\62\325\0"+
    "\2\62\52\0\5\62\5\0\2\62\4\0\126\62\6\0"+
    "\3\62\1\0\132\62\1\0\4\62\5\0\53\62\1\0"+
    "\136\62\21\0\33\62\65\0\306\62\112\0\360\62\20\0"+
    "\215\62\103\0\56\62\2\0\15\62\3\0\20\62\12\21"+
    "\2\62\24\0\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\62\20\0\1\62\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\3\41\2\0"+
    "\106\62\61\0\11\62\2\0\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\3\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\27\12\41"+
    "\1\27\1\41\1\27\1\41\2\27\1\41\1\27\1\41"+
    "\1\27\1\41\1\27\1\41\1\27\1\41\1\62\2\0"+
    "\1\27\1\41\1\27\1\41\1\62\1\27\1\41\1\27"+
    "\3\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\1\27\1\41\5\27\1\41\5\27"+
    "\1\41\1\27\1\41\1\27\1\41\1\27\1\41\1\27"+
    "\1\41\1\27\1\41\2\0\1\27\1\41\3\27\60\0"+
    "\1\62\3\41\7\62\1\0\3\62\1\0\4\62\1\0"+
    "\27\62\35\0\64\62\16\0\62\62\34\0\12\21\30\0"+
    "\6\62\3\0\1\62\1\0\2\62\1\0\12\21\34\62"+
    "\12\0\27\62\31\0\35\62\7\0\57\62\34\0\1\62"+
    "\12\21\6\0\5\62\1\0\12\62\12\21\5\62\1\0"+
    "\51\62\27\0\3\62\1\0\10\62\4\0\12\21\6\0"+
    "\27\62\3\0\1\62\3\0\62\62\1\0\1\62\3\0"+
    "\2\62\2\0\5\62\2\0\1\62\1\0\1\62\30\0"+
    "\3\62\2\0\13\62\7\0\3\62\14\0\6\62\2\0"+
    "\6\62\2\0\6\62\11\0\7\62\1\0\7\62\1\0"+
    "\53\41\1\0\14\41\10\0\120\41\43\62\15\0\12\21"+
    "\6\0\244\62\14\0\27\62\4\0\61\62\4\0\u0100\3"+
    "\156\62\2\0\152\62\46\0\7\41\14\0\5\41\5\0"+
    "\1\62\1\0\12\62\1\0\15\62\1\0\5\62\1\0"+
    "\1\62\1\0\2\62\1\0\2\62\1\0\154\62\41\0"+
    "\153\62\22\0\100\62\2\0\66\62\50\0\14\62\164\0"+
    "\5\62\1\0\207\62\23\0\12\21\7\0\32\27\6\0"+
    "\32\41\13\0\131\62\3\0\6\62\2\0\6\62\2\0"+
    "\6\62\2\0\3\62\43\0\14\62\1\0\32\62\1\0"+
    "\23\62\1\0\2\62\1\0\17\62\2\0\16\62\42\0"+
    "\173\62\205\0\35\62\3\0\61\62\57\0\40\62\15\0"+
    "\24\62\1\0\10\62\6\0\46\62\12\0\36\62\2\0"+
    "\44\62\4\0\10\62\60\0\50\27\50\41\116\62\2\0"+
    "\12\21\6\0\44\27\4\0\44\41\4\0\50\62\10\0"+
    "\64\62\234\0\67\62\11\0\26\62\12\0\10\62\230\0"+
    "\6\62\2\0\1\62\1\0\54\62\1\0\2\62\3\0"+
    "\1\62\2\0\27\62\12\0\27\62\11\0\37\62\101\0"+
    "\23\62\1\0\2\62\12\0\26\62\12\0\32\62\106\0"+
    "\70\62\6\0\2\62\100\0\1\62\17\0\4\62\1\0"+
    "\3\62\1\0\35\62\52\0\35\62\3\0\35\62\43\0"+
    "\10\62\1\0\34\62\33\0\66\62\12\0\26\62\12\0"+
    "\23\62\15\0\22\62\156\0\111\62\67\0\63\27\15\0"+
    "\63\41\15\0\44\62\14\0\12\21\306\0\35\62\12\0"+
    "\1\62\10\0\26\62\232\0\27\62\14\0\65\62\56\0"+
    "\12\21\23\0\55\62\40\0\31\62\7\0\12\21\11\0"+
    "\44\62\17\0\12\21\4\0\1\62\13\0\43\62\3\0"+
    "\1\62\14\0\60\62\16\0\4\62\13\0\12\21\1\62"+
    "\1\0\1\62\43\0\22\62\1\0\31\62\124\0\7\62"+
    "\1\0\1\62\1\0\4\62\1\0\17\62\1\0\12\62"+
    "\7\0\57\62\21\0\12\21\13\0\10\62\2\0\2\62"+
    "\2\0\26\62\1\0\7\62\1\0\2\62\1\0\5\62"+
    "\3\0\1\62\22\0\1\62\14\0\5\62\236\0\65\62"+
    "\22\0\4\62\5\0\12\21\5\0\1\62\40\0\60\62"+
    "\24\0\2\62\1\0\1\62\10\0\12\21\246\0\57\62"+
    "\51\0\4\62\44\0\60\62\24\0\1\62\13\0\12\21"+
    "\46\0\53\62\15\0\1\62\7\0\12\21\66\0\33\62"+
    "\25\0\12\21\306\0\54\62\164\0\40\27\40\41\12\21"+
    "\25\0\1\62\240\0\10\62\2\0\47\62\20\0\1\62"+
    "\1\0\1\62\34\0\1\62\12\0\50\62\7\0\1\62"+
    "\25\0\1\62\13\0\56\62\23\0\1\62\42\0\71\62"+
    "\7\0\11\62\1\0\45\62\21\0\1\62\17\0\12\21"+
    "\30\0\36\62\160\0\7\62\1\0\2\62\1\0\46\62"+
    "\25\0\1\62\11\0\12\21\6\0\6\62\1\0\2\62"+
    "\1\0\40\62\16\0\1\62\7\0\12\21\u0136\0\23\62"+
    "\15\0\232\62\346\0\304\62\274\0\57\62\321\0\107\62"+
    "\271\0\71\62\7\0\37\62\1\0\12\21\146\0\36\62"+
    "\22\0\60\62\20\0\4\62\14\0\12\21\11\0\25\62"+
    "\5\0\23\62\260\0\40\27\40\41\200\0\113\62\5\0"+
    "\1\62\102\0\15\62\100\0\2\62\1\0\1\62\34\0"+
    "\370\62\10\0\363\62\15\0\37\62\61\0\3\62\21\0"+
    "\4\62\10\0\u018c\62\4\0\153\62\5\0\15\62\3\0"+
    "\11\62\7\0\12\62\146\0\32\27\32\41\32\27\7\41"+
    "\1\0\22\41\32\27\32\41\1\27\1\0\2\27\2\0"+
    "\1\27\2\0\2\27\2\0\4\27\1\0\10\27\4\41"+
    "\1\0\1\41\1\0\7\41\1\0\13\41\32\27\32\41"+
    "\2\27\1\0\4\27\2\0\10\27\1\0\7\27\1\0"+
    "\32\41\2\27\1\0\4\27\1\0\5\27\1\0\1\27"+
    "\3\0\7\27\1\0\32\41\32\27\32\41\32\27\32\41"+
    "\32\27\32\41\32\27\32\41\32\27\32\41\32\27\34\41"+
    "\2\0\31\27\1\0\31\41\1\0\6\41\31\27\1\0"+
    "\31\41\1\0\6\41\31\27\1\0\31\41\1\0\6\41"+
    "\31\27\1\0\31\41\1\0\6\41\31\27\1\0\31\41"+
    "\1\0\6\41\1\27\1\41\2\0\62\21\55\62\12\0"+
    "\7\62\2\0\12\21\4\0\1\62\u0171\0\54\62\4\0"+
    "\12\21\6\0\305\62\73\0\42\27\42\41\7\0\1\62"+
    "\4\0\12\21\246\0\4\62\1\0\33\62\1\0\2\62"+
    "\1\0\1\62\2\0\1\62\1\0\12\62\1\0\4\62"+
    "\1\0\1\62\1\0\1\62\6\0\1\62\4\0\1\62"+
    "\1\0\1\62\1\0\1\62\1\0\3\62\1\0\2\62"+
    "\1\0\1\62\2\0\1\62\1\0\1\62\1\0\1\62"+
    "\1\0\1\62\1\0\1\62\1\0\2\62\1\0\1\62"+
    "\2\0\4\62\1\0\7\62\1\0\4\62\1\0\4\62"+
    "\1\0\1\62\1\0\12\62\1\0\21\62\5\0\3\62"+
    "\1\0\5\62\1\0\21\62\164\0\32\64\6\0\32\64"+
    "\6\0\32\64\166\0\327\62\51\0\65\62\13\0\336\62"+
    "\2\0\u0182\62\16\0\u0131\62\37\0\36\62\342\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[28928];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\5\25\1\26\1\27"+
    "\1\30\11\31\1\32\1\33\1\25\1\34\3\1\1\35"+
    "\1\36\3\0\1\37\4\34\3\31\1\40\6\31\1\41"+
    "\1\42\1\1\1\43\3\34\1\44\4\31\1\45\5\31"+
    "\1\46\1\47\1\34\1\50\1\51\2\31\1\52\1\31"+
    "\1\53\1\31\1\54\1\55\1\56\1\31\1\57\2\31"+
    "\1\60\1\61";

  private static int [] zzUnpackAction() {
    int [] result = new int[104];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\152\0\237\0\324\0\152\0\u0109"+
    "\0\152\0\152\0\152\0\152\0\152\0\u013e\0\u0173\0\152"+
    "\0\u01a8\0\152\0\152\0\152\0\u01dd\0\152\0\u0212\0\u0247"+
    "\0\u027c\0\u02b1\0\u02e6\0\152\0\152\0\152\0\u031b\0\u0350"+
    "\0\u0385\0\u03ba\0\u03ef\0\u0424\0\u0459\0\u048e\0\u04c3\0\u04f8"+
    "\0\152\0\152\0\u0212\0\u052d\0\u0562\0\152\0\152\0\152"+
    "\0\u0597\0\u05cc\0\u0173\0\152\0\u0601\0\u0636\0\u066b\0\u06a0"+
    "\0\u06d5\0\u070a\0\u073f\0\u031b\0\u0774\0\u07a9\0\u07de\0\u0813"+
    "\0\u0848\0\u087d\0\152\0\152\0\u08b2\0\152\0\u08e7\0\u091c"+
    "\0\u0951\0\u0212\0\u0986\0\u09bb\0\u09f0\0\u0a25\0\u031b\0\u0a5a"+
    "\0\u0a8f\0\u0ac4\0\u0af9\0\u0b2e\0\u0212\0\u0212\0\u0b63\0\u031b"+
    "\0\u031b\0\u0b98\0\u0bcd\0\u031b\0\u0c02\0\u031b\0\u0c37\0\u031b"+
    "\0\u0212\0\u031b\0\u0c6c\0\u031b\0\u0ca1\0\u0cd6\0\u031b\0\u031b";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[104];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\3\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\3\2\37"+
    "\1\40\1\41\1\42\1\37\1\43\1\37\1\44\1\37"+
    "\1\45\1\46\1\37\1\47\2\37\1\50\1\51\1\52"+
    "\1\37\1\53\16\54\1\55\42\54\1\56\3\54\67\0"+
    "\1\4\107\0\1\57\47\0\1\60\72\0\1\61\67\0"+
    "\1\62\62\0\1\63\1\0\1\21\70\0\1\64\60\0"+
    "\1\53\5\0\5\53\3\0\21\53\2\0\1\53\23\0"+
    "\1\53\5\0\5\53\3\0\12\53\1\65\6\53\2\0"+
    "\1\53\23\0\1\53\5\0\5\53\3\0\6\53\1\66"+
    "\12\53\2\0\1\53\23\0\1\53\5\0\5\53\3\0"+
    "\10\53\1\67\10\53\2\0\1\53\23\0\1\53\5\0"+
    "\5\53\3\0\11\53\1\70\7\53\2\0\1\53\23\0"+
    "\1\37\5\0\5\37\3\0\21\37\2\0\1\37\23\0"+
    "\1\37\5\0\5\37\3\0\1\37\1\71\17\37\2\0"+
    "\1\37\23\0\1\37\5\0\5\37\3\0\10\37\1\72"+
    "\10\37\2\0\1\37\23\0\1\37\5\0\5\37\3\0"+
    "\1\37\1\73\17\37\2\0\1\37\23\0\1\37\5\0"+
    "\5\37\3\0\5\37\1\74\10\37\1\75\2\37\2\0"+
    "\1\37\23\0\1\37\5\0\5\37\3\0\4\37\1\76"+
    "\12\37\1\77\1\37\2\0\1\37\23\0\1\37\5\0"+
    "\5\37\3\0\14\37\1\100\4\37\2\0\1\37\23\0"+
    "\1\37\5\0\5\37\3\0\4\37\1\101\14\37\2\0"+
    "\1\37\23\0\1\37\5\0\5\37\3\0\14\37\1\102"+
    "\4\37\2\0\1\37\20\0\1\103\46\0\16\54\1\0"+
    "\42\54\1\0\3\54\61\0\1\104\3\0\2\61\1\56"+
    "\2\0\1\105\57\61\21\0\1\62\1\0\1\106\62\0"+
    "\1\53\5\0\5\53\3\0\12\53\1\107\6\53\2\0"+
    "\1\53\23\0\1\53\5\0\5\53\3\0\1\53\1\110"+
    "\17\53\2\0\1\53\23\0\1\53\5\0\5\53\3\0"+
    "\12\53\1\111\6\53\2\0\1\53\23\0\1\53\5\0"+
    "\5\53\3\0\16\53\1\112\2\53\2\0\1\53\23\0"+
    "\1\37\5\0\5\37\3\0\16\37\1\113\2\37\2\0"+
    "\1\37\23\0\1\37\5\0\5\37\3\0\15\37\1\114"+
    "\3\37\2\0\1\37\23\0\1\37\5\0\5\37\3\0"+
    "\10\37\1\115\10\37\2\0\1\37\23\0\1\37\5\0"+
    "\5\37\3\0\4\37\1\116\14\37\2\0\1\37\23\0"+
    "\1\37\5\0\5\37\3\0\20\37\1\117\2\0\1\37"+
    "\23\0\1\37\5\0\5\37\3\0\10\37\1\120\10\37"+
    "\2\0\1\37\23\0\1\37\5\0\5\37\3\0\7\37"+
    "\1\121\11\37\2\0\1\37\23\0\1\37\5\0\5\37"+
    "\3\0\1\37\1\122\14\37\1\123\2\37\2\0\1\37"+
    "\23\0\1\37\5\0\5\37\3\0\17\37\1\124\1\37"+
    "\2\0\1\37\4\0\1\56\103\0\1\53\5\0\5\53"+
    "\3\0\10\53\1\125\10\53\2\0\1\53\23\0\1\53"+
    "\5\0\5\53\3\0\14\53\1\126\4\53\2\0\1\53"+
    "\23\0\1\53\5\0\5\53\3\0\1\53\1\127\17\53"+
    "\2\0\1\53\23\0\1\37\5\0\5\37\3\0\1\37"+
    "\1\130\17\37\2\0\1\37\23\0\1\37\5\0\5\37"+
    "\3\0\4\37\1\131\14\37\2\0\1\37\23\0\1\37"+
    "\5\0\5\37\3\0\15\37\1\132\3\37\2\0\1\37"+
    "\23\0\1\37\5\0\5\37\3\0\14\37\1\133\4\37"+
    "\2\0\1\37\23\0\1\37\5\0\5\37\3\0\10\37"+
    "\1\134\10\37\2\0\1\37\23\0\1\37\5\0\5\37"+
    "\3\0\11\37\1\135\7\37\2\0\1\37\23\0\1\37"+
    "\5\0\5\37\3\0\3\37\1\136\15\37\2\0\1\37"+
    "\23\0\1\37\5\0\5\37\3\0\17\37\1\137\1\37"+
    "\2\0\1\37\23\0\1\37\5\0\5\37\3\0\4\37"+
    "\1\140\14\37\2\0\1\37\23\0\1\53\5\0\5\53"+
    "\3\0\16\53\1\141\2\53\2\0\1\53\23\0\1\37"+
    "\5\0\5\37\3\0\4\37\1\142\14\37\2\0\1\37"+
    "\23\0\1\37\5\0\5\37\3\0\1\37\1\143\17\37"+
    "\2\0\1\37\23\0\1\37\5\0\5\37\3\0\16\37"+
    "\1\144\2\37\2\0\1\37\23\0\1\37\5\0\5\37"+
    "\3\0\14\37\1\145\4\37\2\0\1\37\23\0\1\37"+
    "\5\0\5\37\3\0\16\37\1\146\2\37\2\0\1\37"+
    "\23\0\1\37\5\0\5\37\3\0\11\37\1\147\7\37"+
    "\2\0\1\37\23\0\1\37\5\0\5\37\3\0\4\37"+
    "\1\150\14\37\2\0\1\37\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3339];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\1\2\11\2\1\1\11\1\1\5\11\2\1"+
    "\1\11\1\1\3\11\1\1\1\11\5\1\3\11\12\1"+
    "\2\11\3\1\3\11\3\0\1\11\16\1\2\11\1\1"+
    "\1\11\42\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[104];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    
    
    private int ntk; // Contador de numero de tokens lidos
    
    public int readedTokens(){ // Retornar o numero de tokens lidos
       return ntk;
    }
    private Token symbol(TOKEN_TYPE t) {//  Constroi um token
        ntk++;
        return new Token(t,yytext(), yyline+1, yycolumn+1);
        
    }
    private Token symbol(TOKEN_TYPE t, Object value) {// Constroi um token com valor associado
        ntk++;
        return new Token(t, value, yyline+1, yycolumn+1);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
      ntk = 0;  
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token nextToken() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { 
            }
            // fall through
          case 50: break;
          case 2:
            { throw new RuntimeException("Illegal character <"+yytext()+">");
            }
            // fall through
          case 51: break;
          case 3:
            { /* Não faz nada  */
            }
            // fall through
          case 52: break;
          case 4:
            { return symbol(TOKEN_TYPE.NOT_SIGN);
            }
            // fall through
          case 53: break;
          case 5:
            { return symbol(TOKEN_TYPE.MOD_SIGN);
            }
            // fall through
          case 54: break;
          case 6:
            { return symbol(TOKEN_TYPE.AMPERSAND);
            }
            // fall through
          case 55: break;
          case 7:
            { return symbol(TOKEN_TYPE.SINGLE_QUOTES);
            }
            // fall through
          case 56: break;
          case 8:
            { return symbol(TOKEN_TYPE.OPEN_PARENT);
            }
            // fall through
          case 57: break;
          case 9:
            { return symbol(TOKEN_TYPE.MULT_SIGN);
            }
            // fall through
          case 58: break;
          case 10:
            { return symbol(TOKEN_TYPE.PLUS_SIGN);
            }
            // fall through
          case 59: break;
          case 11:
            { return symbol(TOKEN_TYPE.COMMA);
            }
            // fall through
          case 60: break;
          case 12:
            { return symbol(TOKEN_TYPE.MINUS_SIGN);
            }
            // fall through
          case 61: break;
          case 13:
            { return symbol(TOKEN_TYPE.DOT);
            }
            // fall through
          case 62: break;
          case 14:
            { return symbol(TOKEN_TYPE.DIVIDE_SIGN);
            }
            // fall through
          case 63: break;
          case 15:
            { return symbol(TOKEN_TYPE.INT_VAL, Integer.parseInt(yytext()) );
            }
            // fall through
          case 64: break;
          case 16:
            { return symbol(TOKEN_TYPE.DOUBLE_COLON);
            }
            // fall through
          case 65: break;
          case 17:
            { return symbol(TOKEN_TYPE.SEMICOLON);
            }
            // fall through
          case 66: break;
          case 18:
            { return symbol(TOKEN_TYPE.LESSER_THAN);
            }
            // fall through
          case 67: break;
          case 19:
            { return symbol(TOKEN_TYPE.EQUAL);
            }
            // fall through
          case 68: break;
          case 20:
            { return symbol(TOKEN_TYPE.GREATER_THAN);
            }
            // fall through
          case 69: break;
          case 21:
            { return symbol(TOKEN_TYPE.CHAR_VAL);
            }
            // fall through
          case 70: break;
          case 22:
            { return symbol(TOKEN_TYPE.OPEN_BRACE);
            }
            // fall through
          case 71: break;
          case 23:
            { return symbol(TOKEN_TYPE.BACK_SLASH);
            }
            // fall through
          case 72: break;
          case 24:
            { return symbol(TOKEN_TYPE.CLOSE_BRACE);
            }
            // fall through
          case 73: break;
          case 25:
            { return symbol(TOKEN_TYPE.ID);
            }
            // fall through
          case 74: break;
          case 26:
            { return symbol(TOKEN_TYPE.OPEN_BRECKET);
            }
            // fall through
          case 75: break;
          case 27:
            { return symbol(TOKEN_TYPE.CLOSE_BRECKET);
            }
            // fall through
          case 76: break;
          case 28:
            { return symbol(TOKEN_TYPE.NAME_VAL);
            }
            // fall through
          case 77: break;
          case 29:
            { return symbol(TOKEN_TYPE.NOT_EQUAL_SIGN);
            }
            // fall through
          case 78: break;
          case 30:
            { return symbol(TOKEN_TYPE.AND_SIGN);
            }
            // fall through
          case 79: break;
          case 31:
            { return symbol(TOKEN_TYPE.EQUALITY_SIGN);
            }
            // fall through
          case 80: break;
          case 32:
            { return symbol(TOKEN_TYPE.IF);
            }
            // fall through
          case 81: break;
          case 33:
            { yybegin(COMMENT);
            }
            // fall through
          case 82: break;
          case 34:
            { yybegin(YYINITIAL);
            }
            // fall through
          case 83: break;
          case 35:
            { return symbol(TOKEN_TYPE.FLOAT_VAL, Float.parseFloat(yytext()) );
            }
            // fall through
          case 84: break;
          case 36:
            { return symbol(TOKEN_TYPE.INT);
            }
            // fall through
          case 85: break;
          case 37:
            { return symbol(TOKEN_TYPE.NEW);
            }
            // fall through
          case 86: break;
          case 38:
            { return symbol(TOKEN_TYPE.BOOL);
            }
            // fall through
          case 87: break;
          case 39:
            { return symbol(TOKEN_TYPE.CHAR);
            }
            // fall through
          case 88: break;
          case 40:
            { return symbol(TOKEN_TYPE.DATA);
            }
            // fall through
          case 89: break;
          case 41:
            { return symbol(TOKEN_TYPE.ELSE);
            }
            // fall through
          case 90: break;
          case 42:
            { return symbol(TOKEN_TYPE.NULL);
            }
            // fall through
          case 91: break;
          case 43:
            { return symbol(TOKEN_TYPE.READ);
            }
            // fall through
          case 92: break;
          case 44:
            { return symbol(TOKEN_TYPE.TRUE);
            }
            // fall through
          case 93: break;
          case 45:
            { return symbol(TOKEN_TYPE.FLOAT);
            }
            // fall through
          case 94: break;
          case 46:
            { return symbol(TOKEN_TYPE.FALSE);
            }
            // fall through
          case 95: break;
          case 47:
            { return symbol(TOKEN_TYPE.PRINT);
            }
            // fall through
          case 96: break;
          case 48:
            { return symbol(TOKEN_TYPE.RETURN);
            }
            // fall through
          case 97: break;
          case 49:
            { return symbol(TOKEN_TYPE.ITERATE);
            }
            // fall through
          case 98: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
